#Random port
server:
  port: 0
  
spring:
  application:
    name: zuul-gateway  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
ribbon:
  eureka:
    enabled: true
      
zuul:
  prefix: /api/school
  routes:
    crud:
      path: /db/**
      service-id: crud-service
    student:
      path: /student/**
      service-id: student-service
    comunicado:
      path: /comunicado/**
      service-id: comunicado-service
    financial:
      path: /financial/**
      service-id: financial-service